package e

const (
	SUCCESS        = 0
	INTERNAL_ERROR = -1
	UKNOWN_ERROR   = -2

	ERROR_READFILE = -3

	EXTERNAL_API_ERROR = -4

	NOVEL_PROVIDER_URL_NOT_SUPPORT   = -5
	NOVEL_PROVIDER_URL_NOT_SUPPORT_2 = -6
)
