package e

const (
	SUCCESS        = 0
	INTERNAL_ERROR = -1

	// music
	MUSIC_ERROR_PROVIDER_NOT_AVAILABLE = 101
	MUSIC_ERROR_SEARCH_FAIL            = 102
	MUSIC_ERROR_INITIALIZE_FAIL        = 103
	MUSIC_ERROR_GET_DATA_FAIL          = 104

	// Context
	CONTEXT_ERROR_NOT_IN_VOICE_CHANNEL = 201

	// Musicbot
	MUSICBOT_ERROR_QUEUE_EMPTY             = 301
	MUSICBOT_ERROR_ALREADY_PAUSED_UNPAUSED = 302
	MUSICBOT_ERROR_NOT_PLAYING             = 302
)
