// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/anime/info": {
            "get": {
                "description": "获取动漫信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "get anime info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "susudm-17891-acg-1",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/anime/info/{provider}": {
            "get": {
                "description": "根据来源获取动漫信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "get anime info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "anime provider identifier",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "susudm?uid=susudm-17891-acg-1",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/anime/playurl": {
            "get": {
                "description": "获取动漫播放地址",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "get anime playurl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "susudm-17891-acg-1",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/anime/playurl/{provider}": {
            "get": {
                "description": "根据来源获取动漫播放地址",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "get anime playurl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "anime provider identifier",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "susudm?uid=susudm-17891-acg-1",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/anime/resolve": {
            "get": {
                "description": "解析动漫",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "resolve anime",
                "parameters": [
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "susudm-17891-acg-1, http://susudm.com/acg/17891/",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/anime/resolve/{provider}": {
            "get": {
                "description": "根据来源解析动漫",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "resolve anime",
                "parameters": [
                    {
                        "type": "string",
                        "description": "anime provider identifier",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "susudm?url=susudm-17891-acg-1, susudm?url=http://susudm.com/acg/17891/",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/anime/search": {
            "get": {
                "description": "搜索动漫",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "search anime",
                "parameters": [
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刀剑神域",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/anime/search/{provider}": {
            "get": {
                "description": "根据来源搜索动漫",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "search anime",
                "parameters": [
                    {
                        "type": "string",
                        "description": "anime provider identifier",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "susudm?keyword=刀剑神域",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novel/content": {
            "get": {
                "description": "获取小说章节内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "get novel content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "content url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "https://www.linovelib.com/novel/2342/133318.html",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novel/info": {
            "get": {
                "description": "获取小说简介",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "get novel info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "info page url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "https://www.linovelib.com/novel/8.html",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novel/providerlist": {
            "get": {
                "description": "获取来源列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "get provider list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novel/rulelist": {
            "get": {
                "description": "获取来源规则",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "get provider rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novel/search": {
            "get": {
                "description": "搜索小说",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "search novel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "诡秘之主",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/novel/search/{provider}": {
            "get": {
                "description": "根据来源搜索小说",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "search novel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "novel provider identifier",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "biqugeB?keyword=诡秘之主",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.AppJsonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
