// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/info": {
            "get": {
                "description": "获取当前用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "get current user info",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "get": {
                "description": "登录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "login",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "get": {
                "description": "登出",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "logout",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v2/anime/info": {
            "get": {
                "description": "根据metadata获取动漫信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "get anime info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "anime provider meta id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.AnimeInfo"
                        }
                    }
                }
            }
        },
        "/api/v2/anime/playurl": {
            "get": {
                "description": "获取动漫播放地址",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "get anime playurl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "anime provider meta id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "playlist id",
                        "name": "pid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "episode id",
                        "name": "eid",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.AnimePlayUrl"
                        }
                    }
                }
            }
        },
        "/api/v2/anime/providerlist": {
            "get": {
                "description": "获取来源列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "get provider list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.AnimeProviderList"
                        }
                    }
                }
            }
        },
        "/api/v2/anime/search": {
            "get": {
                "description": "搜索动漫",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "search anime",
                "parameters": [
                    {
                        "type": "string",
                        "description": "keyword (e.g. 刀剑神域)",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.AnimeSearchResult"
                        }
                    }
                }
            }
        },
        "/api/v2/anime/search/{provider}": {
            "get": {
                "description": "根据来源搜索动漫",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "search anime",
                "parameters": [
                    {
                        "type": "string",
                        "description": "anime provider identifier (e.g. susudm)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "keyword (e.g. 刀剑神域)",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.AnimeSearchResult"
                        }
                    }
                }
            }
        },
        "/api/v2/auth/info": {
            "get": {
                "description": "获取当前用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "get current user info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.UserPublicInfo"
                        }
                    }
                }
            }
        },
        "/api/v2/auth/login": {
            "get": {
                "description": "登录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.LoginResp"
                        }
                    }
                }
            }
        },
        "/api/v2/auth/logout": {
            "get": {
                "description": "登出",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v2/music/info": {
            "get": {
                "description": "根据metadata获取音乐信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Music"
                ],
                "summary": "get music info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "music provider meta id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.MusicInfo"
                        }
                    }
                }
            }
        },
        "/api/v2/music/providerlist": {
            "get": {
                "description": "获取来源列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Music"
                ],
                "summary": "get provider list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.MusicProviderList"
                        }
                    }
                }
            }
        },
        "/api/v2/music/search": {
            "get": {
                "description": "搜索音乐",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Music"
                ],
                "summary": "search music",
                "parameters": [
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.MusicSearchResult"
                        }
                    }
                }
            }
        },
        "/api/v2/music/search/{provider}": {
            "get": {
                "description": "根据来源搜索音乐",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Music"
                ],
                "summary": "search music",
                "parameters": [
                    {
                        "type": "string",
                        "description": "music provider identifier (e.g. bilibilimusic)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "keyword (e.g. 霜雪千年)",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.MusicSearchResult"
                        }
                    }
                }
            }
        },
        "/api/v2/music/url": {
            "get": {
                "description": "获取音乐播放地址",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Music"
                ],
                "summary": "get music playurl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "music provider meta id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "specify user agent",
                        "name": "ua",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.MusicPlayUrl"
                        }
                    }
                }
            }
        },
        "/api/v2/novel/content": {
            "get": {
                "description": "获取小说章节内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "get novel content",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "novel provider meta id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "volume id",
                        "name": "vid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "chapter id",
                        "name": "cid",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "https://www.linovelib.com/novel/2342/133318.html",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v2/novel/info": {
            "get": {
                "description": "获取小说简介",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "get novel info",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "novel provider meta id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v2/novel/providerlist": {
            "get": {
                "description": "获取来源列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "get provider list",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v2/novel/search": {
            "get": {
                "description": "搜索小说",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "search novel",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "诡秘之主",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        },
        "/api/v2/novel/search/{provider}": {
            "get": {
                "description": "根据来源搜索小说",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Novel"
                ],
                "summary": "search novel",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "novel provider identifier",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "use cache",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "biqugeB?keyword=诡秘之主",
                        "schema": {
                            "$ref": "#/definitions/app.AppJsonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "anime.Anime": {
            "type": "object",
            "properties": {
                "cover": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "playlists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/anime.Playlist"
                    }
                },
                "provider": {
                    "$ref": "#/definitions/core.ProviderMeta"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "anime.AnimeMeta": {
            "type": "object",
            "properties": {
                "cover": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "provider": {
                    "$ref": "#/definitions/core.ProviderMeta"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "anime.AnimeVideo": {
            "type": "object",
            "properties": {
                "provider": {
                    "$ref": "#/definitions/core.ProviderMeta"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "anime.Playlist": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/anime.AnimeVideo"
                    }
                }
            }
        },
        "app.AppJsonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "core.ProviderMeta": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "music.Music": {
            "type": "object",
            "properties": {
                "album": {
                    "type": "string"
                },
                "artist": {
                    "type": "string"
                },
                "audio": {
                    "$ref": "#/definitions/music.MusicAudio"
                },
                "cover": {
                    "type": "string"
                },
                "lyric": {
                    "$ref": "#/definitions/music.MusicLyric"
                },
                "provider": {
                    "$ref": "#/definitions/core.ProviderMeta"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "music.MusicAudio": {
            "type": "object",
            "properties": {
                "provider": {
                    "$ref": "#/definitions/core.ProviderMeta"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        },
        "music.MusicLyric": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                }
            }
        },
        "music.MusicMeta": {
            "type": "object",
            "properties": {
                "album": {
                    "type": "string"
                },
                "artist": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "provider": {
                    "$ref": "#/definitions/core.ProviderMeta"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "resp.AnimeInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/anime.Anime"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.AnimePlayUrl": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/anime.AnimeVideo"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.AnimeProviderList": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.AnimeSearchResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/anime.AnimeMeta"
                        }
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.LoginResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "token": "token1234"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.MusicInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/music.Music"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.MusicPlayUrl": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/music.MusicAudio"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.MusicProviderList": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.MusicSearchResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/music.MusicMeta"
                        }
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.PublicInfo": {
            "type": "object",
            "properties": {
                "permission": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "resp.UserPublicInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/resp.PublicInfo"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
