definitions:
  app.AppJsonResponse:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/info:
    get:
      description: 获取当前用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: get current user info
      tags:
      - Auth
  /api/v1/auth/login:
    get:
      description: 登录
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: login
      tags:
      - Auth
  /api/v2/anime/info:
    get:
      description: 根据metadata获取动漫信息
      parameters:
      - description: anime provider meta id
        in: query
        name: mid
        required: true
        type: string
      - description: use cache
        in: query
        name: cache
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: xxxxxxx
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: get anime info
      tags:
      - Anime
  /api/v2/anime/playurl:
    get:
      description: 获取动漫播放地址
      parameters:
      - description: anime provider meta id
        in: query
        name: mid
        required: true
        type: string
      - description: playlist id
        in: query
        name: pid
        type: integer
      - description: episode id
        in: query
        name: eid
        type: integer
      - description: use cache
        in: query
        name: cache
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: xxxxxxx
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: get anime playurl
      tags:
      - Anime
  /api/v2/anime/providerlist:
    get:
      description: 获取来源列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: get provider list
      tags:
      - Anime
  /api/v2/anime/search:
    get:
      description: 搜索动漫
      parameters:
      - description: keyword
        in: query
        name: keyword
        required: true
        type: string
      - description: use cache
        in: query
        name: cache
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 刀剑神域
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: search anime
      tags:
      - Anime
  /api/v2/anime/search/{provider}:
    get:
      description: 根据来源搜索动漫
      parameters:
      - description: anime provider identifier
        in: path
        name: provider
        required: true
        type: string
      - description: keyword
        in: query
        name: keyword
        required: true
        type: string
      - description: use cache
        in: query
        name: cache
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: susudm?keyword=刀剑神域
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: search anime
      tags:
      - Anime
  /api/v2/novel/content:
    get:
      description: 获取小说章节内容
      parameters:
      - description: novel provider meta id
        in: query
        name: mid
        required: true
        type: string
      - description: volume id
        in: query
        name: vid
        type: integer
      - description: chapter id
        in: query
        name: cid
        type: integer
      - description: use cache
        in: query
        name: cache
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: https://www.linovelib.com/novel/2342/133318.html
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: get novel content
      tags:
      - Novel
  /api/v2/novel/info:
    get:
      description: 获取小说简介
      parameters:
      - description: novel provider meta id
        in: query
        name: mid
        required: true
        type: string
      - description: use cache
        in: query
        name: cache
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: get novel info
      tags:
      - Novel
  /api/v2/novel/providerlist:
    get:
      description: 获取来源列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: get provider list
      tags:
      - Novel
  /api/v2/novel/search:
    get:
      description: 搜索小说
      parameters:
      - description: keyword
        in: query
        name: keyword
        required: true
        type: string
      - description: use cache
        in: query
        name: cache
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: 诡秘之主
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: search novel
      tags:
      - Novel
  /api/v2/novel/search/{provider}:
    get:
      description: 根据来源搜索小说
      parameters:
      - description: novel provider identifier
        in: path
        name: provider
        required: true
        type: string
      - description: keyword
        in: query
        name: keyword
        required: true
        type: string
      - description: use cache
        in: query
        name: cache
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: biqugeB?keyword=诡秘之主
          schema:
            $ref: '#/definitions/app.AppJsonResponse'
      summary: search novel
      tags:
      - Novel
swagger: "2.0"
