# docker-image.yml
name: Build & Push Docker Image

# 配置触发workflow的事件
on:
  push:
#    branches: # master分支有push时触发此workflow
#      - 'master'
    tags: # tag更新时触发此workflow
      - '*'

jobs: # workflow中的job
  build_push_to_docker_hub: # job的名字
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest   # job运行的基础环境

    steps: # 一个job由一个或多个step组成
      # 获取代码
      - name: Check out the repo
        uses: actions/checkout@v3.0.0

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        # username and token
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: aynakeya/aynaapi

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}